language: objective-c
osx_image: xcode9.3
script:
 - xcodebuild -project AsynchronousTestingClosureDependency.xcodeproj -scheme AsynchronousTestingClosureDependency clean test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest'